Add Alex's pubkey
tiiuae/ghaf-infra pull request #189
Opened 2024-06-20 11:33 UTC by alextserepov

2024-06-20 15:57 UTC, joinemm requested changes

2024-06-20 15:57 UTC, joinemm commented on ssh-keys.yaml
> + ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvQdncdNCFMw7f0Xln40H/u0fJp82tVrQMEHtSdvP6m aleksandr.tserepov-savolainen@unikie.com
Indentation of the username is incorrect, and ssh key needs a dash before it

2024-08-02 08:10 UTC, mkaapu approved these changes

2024-08-02 08:12 UTC, joinemm approved these changes

2024-08-02 08:22 UTC, closed without merging