initial host configuration and nixos install for ghaf-proxy
tiiuae/ghaf-infra pull request #259
Opened 2024-10-01 09:48 UTC by fayadf

Initial server configuration for ghaf-proxy server, and initial nixos deployment on top of linux distro. Changes include

1. Configuration for the server
2. Disk formatting and mounts
3. Including the new server into existing deployment
4. Added existing team into server for ssh

2024-10-01 11:10 UTC, joinemm requested changes

2024-10-01 11:23 UTC, karim20230 commented
@fayadf Missing copyright/licensing information

2024-10-02 09:35 UTC, fayadf commented on hosts/default.nix
> +	      "ghaf-proxy"
Fixed indentation

2024-10-02 09:36 UTC, fayadf commented on hosts/ghaf-proxy/configuration.nix
> +      user-vunnyso
Removed users

2024-10-02 09:37 UTC, fayadf commented
@karim20230 Ack! Fixed it.

2024-10-02 11:39 UTC, closed without merging