fix inginx import
tiiuae/ghaf-infra pull request #79
Opened 2024-02-20 09:50 UTC by karim20230

fix inginx import

2024-02-20 13:36 UTC, joinemm approved these changes

2024-02-20 16:25 UTC, tervis-unikie commented
Incorrect subject capitalization

2024-02-20 16:26 UTC, tervis-unikie requested changes
Incorrect subject capitalization.
Take githooks into use and check action outputs when making a PR.

2024-02-21 15:08 UTC, tervis-unikie approved these changes

2024-02-21 15:10 UTC, merged